services:
  - type: web
    name: eventful-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://eventful-backend-vase.onrender.com/api/v1